web_socket:
  host: "127.0.0.1" # ホスト名
  port: 8080 # ポート番号

server:
  self_match: false # 同じチーム名のエージェント同士のみをマッチングさせるか

game:
  agent_count: 5 # 1ゲームあたりのエージェント数
  vote_visibility: false # 投票の結果を公開するか
  talk_on_first_day: true # 1日目の発言を許可するか
  max_continue_error_ratio: 0.2 # ゲームを継続するエラーエージェントの最大割合
  talk:
    max_count:
      per_agent: 3 # 1日あたりの1エージェントの最大発言回数
      per_day: 15 # 1日あたりの全体の発言回数
  whisper:
    max_count:
      per_agent: 3 # 1日あたりの1エージェントの最大囁き回数
      per_day: 15 # 1日あたりの全体の囁き回数
  skip:
    max_count: 3 # 1日あたりの1エージェントの最大スキップ回数
  vote:
    max_count: 1 # 1位タイの場合の最大再投票回数
  attack:
    max_count: 1 # 1位タイの場合の最大襲撃再投票回数
    allow_no_target: true # 襲撃なしの日を許可するか
  timeout:
    action: 60s # エージェントのアクションのタイムアウト時間
    response: 90s # エージェントの生存確認のタイムアウト時間

analysis_service:
  output_dir: "./../log" # 分析結果の出力ディレクトリ

api_service:
  enable: true # APIサービスを有効にするか
  publish_running_game: true # 進行中のゲームを公開するか

match_optimizer:
  output_path: "./../log/match_optimizer.json" # マッチ履歴の出力ファイル
